apiVersion: apps/v1
kind: Deployment
metadata:
  name: markazuna
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: markazuna
  template:
    metadata:
      labels:
        app: markazuna
    spec:
      containers:
      - name: markazuna
        image: asia.gcr.io/plenary-hangout-297905/markazuna:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        workingDir: "/home/app/markazuna.com"