apiVersion: v1
kind: PersistentVolume
metadata:
  name: markazuna-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: markazuna-pvc
  gcePersistentDisk:
    pdName: markazuna
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: markazuna-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G