# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.0-node-browsers
      - image: circleci/mongo:4.0.5

    working_directory: ~/repo
    steps:
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "Gemfile.lock" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run:
          name: install dependencies gems
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: install dependencies node modules
          command: |
            yarn

      # - save_cache:
      #     paths:
      #       - ./vendor/bundle
      #     key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: sudo apt-get install mongodb-clients
      - run: mongo markazuna --eval 'db.createUser({user:"admin",pwd:"password",roles:["readWrite"],passwordDigestor:"server"});'
      - run: mongo markazuna --eval 'db.core_users.insertOne({ email:"admin@gmail.com",username:"admin",password:"password",firstname:"Admin",lastname:"App"});'
      
      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec spec/

      # # collect reports
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: test-results